//export const LOAD_CHECKLISTS = 'LOAD_CHECKLISTS';
export const LOAD_CHECKLISTS_SUCCESS = 'LOAD_CHECKLISTS_SUCCESS';
export const CREATE_CHECKLIST_SUCCESS = 'CREATE_CHECKLIST_SUCCESS';
export const UPDATE_CHECKLIST_SUCCESS = 'UPDATE_CHECKLIST_SUCCESS';

export const LOAD_CHECKLIST = 'LOAD_CHECKLIST';
export const CREATE_CHECKLIST = 'CREATE_CHECKLIST';
export const ADD_CHECKLIST_ITEM = 'ADD_CHECKLIST_ITEM';
export const DELETE_CHECKLIST_ITEM = 'DELETE_CHECKLIST_ITEM';

//export const CREATE_CHECKLIST_TITLE = 'CREATE_CHECKLIST_TITLE';
export const UPDATE_CHECKLIST_TITLE = 'UPDATE_CHECKLIST_TITLE';
export const UPDATE_NEW_CHECKLIST_ID = 'UPDATE_NEW_CHECKLIST_ID';

//export const UPDATE_CHECKLIST = 'UPDATE_CHECKLIST';
