export const LOAD_CHECKLISTS_SUCCESS = 'LOAD_CHECKLISTS_SUCCESS';
export const CREATE_CHECKLIST_SUCCESS = 'CREATE_CHECKLIST_SUCCESS';
export const UPDATE_CHECKLIST_SUCCESS = 'UPDATE_CHECKLIST_SUCCESS';
