export const CREATE_CHECKLIST_TITLE = 'CREATE_CHECKLIST_TITLE';
export const LOAD_CHECKLIST_ITEMS = 'LOAD_CHECKLIST_ITEMS';
export const CREATE_CHECKLIST_ITEM = 'CREATE_CHECKLIST_ITEM';
export const UPDATE_CHECKLIST = 'UPDATE_CHECKLIST';
export const DELETE_CHECKLIST_ITEM = 'DELETE_CHECKLIST_ITEM;'